In [194]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [195]:
from tensorflow.keras.preprocessing.text import one_hot

In [196]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [197]:
### Vocabulary size intialize
voc_size=500

In [198]:
onehot_repr=[one_hot(words,voc_size) for words in sent]
onehot_repr

[[355, 360, 152, 126],
 [355, 360, 152, 324],
 [355, 157, 152, 310],
 [487, 108, 380, 373, 360],
 [487, 108, 380, 373, 452],
 [26, 355, 411, 152, 226],
 [402, 341, 306, 373]]

# **Word Embedding Represntation**

In [199]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [200]:
from typing import Sequence
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,maxlen=sent_length,padding="pre")
print(embedded_docs)

[[  0   0   0   0 355 360 152 126]
 [  0   0   0   0 355 360 152 324]
 [  0   0   0   0 355 157 152 310]
 [  0   0   0 487 108 380 373 360]
 [  0   0   0 487 108 380 373 452]
 [  0   0   0  26 355 411 152 226]
 [  0   0   0   0 402 341 306 373]]


In [201]:
## 10 feature dimesnions
dim=10

In [202]:
model=Sequential()
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [203]:
embedded_docs[0]

array([  0,   0,   0,   0, 355, 360, 152, 126], dtype=int32)

In [204]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step


array([[ 0.03956547,  0.00218471, -0.04259519, -0.01561778,  0.00690731,
         0.04506799,  0.00519248, -0.02022278, -0.03929197,  0.04792449],
       [ 0.03956547,  0.00218471, -0.04259519, -0.01561778,  0.00690731,
         0.04506799,  0.00519248, -0.02022278, -0.03929197,  0.04792449],
       [ 0.03956547,  0.00218471, -0.04259519, -0.01561778,  0.00690731,
         0.04506799,  0.00519248, -0.02022278, -0.03929197,  0.04792449],
       [ 0.03956547,  0.00218471, -0.04259519, -0.01561778,  0.00690731,
         0.04506799,  0.00519248, -0.02022278, -0.03929197,  0.04792449],
       [ 0.01642368,  0.04184489,  0.01347059, -0.00356831, -0.04448843,
         0.00476598, -0.02762075, -0.0493829 ,  0.02431914,  0.03261924],
       [ 0.02122876, -0.00453466, -0.03587564, -0.04719031,  0.01274833,
        -0.04946098,  0.03731635, -0.0089156 , -0.02544998,  0.03093702],
       [-0.03164105,  0.00428975, -0.03691261, -0.029101  ,  0.04849025,
         0.0367659 ,  0.03783251, -0.01519091

In [209]:
model.predict(embedded_docs)

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None

In [ ]:
model.summary()

In [ ]:
print(embedded_docs.shape)


In [ ]:
model.predict(embedded_docs[0])

In [ ]:
embedded_docs[0]

In [ ]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [210]:
model=Sequential()
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [211]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step


array([[[ 3.24645527e-02,  2.44440548e-02, -3.04242373e-02,
         -3.18883881e-02, -4.22619954e-02,  1.37844943e-02,
         -2.00203788e-02, -3.34202535e-02, -8.58243555e-03,
          4.35062386e-02],
        [ 3.24645527e-02,  2.44440548e-02, -3.04242373e-02,
         -3.18883881e-02, -4.22619954e-02,  1.37844943e-02,
         -2.00203788e-02, -3.34202535e-02, -8.58243555e-03,
          4.35062386e-02],
        [ 3.24645527e-02,  2.44440548e-02, -3.04242373e-02,
         -3.18883881e-02, -4.22619954e-02,  1.37844943e-02,
         -2.00203788e-02, -3.34202535e-02, -8.58243555e-03,
          4.35062386e-02],
        [ 3.24645527e-02,  2.44440548e-02, -3.04242373e-02,
         -3.18883881e-02, -4.22619954e-02,  1.37844943e-02,
         -2.00203788e-02, -3.34202535e-02, -8.58243555e-03,
          4.35062386e-02],
        [ 4.48689200e-02, -1.79898739e-02, -4.21067700e-02,
          1.16381533e-02, -2.80400049e-02,  8.92706960e-03,
          1.78724043e-02,  8.50796700e-04, -4.767157